In [12]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import pickle

In [13]:
df = pd.read_csv("/content/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [15]:
df["sex"] = df["sex"].map({"male": 1, "female": 0})
df["smoker"] = df["smoker"].map({"yes": 1, "no": 0})
df["region"] = df["region"].map({
    "southwest": 0,
    "southeast": 1,
    "northwest": 2,
    "northeast": 3
})

df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       0  16884.92400
1   18    1  33.770         1       0       1   1725.55230
2   28    1  33.000         3       0       1   4449.46200
3   33    1  22.705         0       0       2  21984.47061
4   32    1  28.880         0       0       2   3866.85520

In [16]:
X = df.drop("charges", axis=1)
y = df["charges"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (1338, 6)
Target shape: (1338,)

In [22]:
mean_values = df.mean(numeric_only=True)
print("Mean values:\n", mean_values)
print('==============================')
median_values = df.median(numeric_only=True)
print("Median values:\n", median_values)
print('==============================')
max_values = df.max(numeric_only=True)
print("Max values:\n", max_values)
print('==============================')
min_values = df.min(numeric_only=True)
print("Min values:\n", min_values)
print('==============================')
std_values = df.std(numeric_only=True)
print("Std values:\n", std_values)

Mean values:
 age            39.207025
sex             0.505232
bmi            30.663397
children        1.094918
smoker          0.204783
region          1.484305
charges     13270.422265
dtype: float64
==============================
Median values:
 age           39.000
sex            1.000
bmi           30.400
children       1.000
smoker         0.000
region         1.000
charges     9382.033
dtype: float64
==============================
Max values:
 age            64.00000
sex             1.00000
bmi            53.13000
children        5.00000
smoker          1.00000
region          3.00000
charges     63770.42801
dtype: float64
==============================
Min values:
 age           18.0000
sex            0.0000
bmi           15.9600
children       0.0000
smoker         0.0000
region         0.0000
charges     1121.8739
dtype: float64
==============================
Std values:
 age            14.049960
sex             0.500160
bmi             6.098187
children        1.205493
smoker          0.403694
region          1.104885
charges     12110.011237
dtype: float64

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [18]:
model = LinearRegression()
model.fit(X_train, y_train)

print("Model training completed")

Model training completed

In [19]:
y_pred = model.predict(X_test)

In [20]:
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.7833463107364539

In [21]:
pickle.dump(model, open("insurance_model.pkl", "wb"))
print("Pickle file saved")

Pickle file saved